# Generated by Django 4.0.3 on 2022-04-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='edad',
            new_name='dni',
        ),
    ]
