# Generated by Django 4.0.3 on 2022-04-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0003_curso_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fechaDeEntrega', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='clase',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='clase',
        ),
        migrations.AddField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(default=11111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default=1111, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(default=11111, max_length=30),
            preserve_default=False,
        ),
    ]
