# Generated by Django 4.0.3 on 2022-04-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0006_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
