# Generated by Django 4.0.3 on 2022-04-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0007_delete_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
