# Generated by Django 4.0.3 on 2022-04-30 19:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0008_message_alter_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
